(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sb=supabase.createClient('https://vqgipvwcvbhabvfipodl.supabase.co','sb_publishable_BYEVImorGhltw1aCaRXyRQ_pM2hKMkI',{auth:{storageKey:'firemap-matka-auth'}});
let data={accounts:[],counties:[],admins:[]},busy=false,areas=[],areaVersion=0;
async function call(body){const r=await sb.functions.invoke('manage-platform',{body});if(r.error){let d;try{d=await r.error.context.json()}catch{}throw Error(d?.error||'Nie udało się połączyć. Sprawdź listę przed ponowieniem.')}if(r.data?.error)throw Error(r.data.error);return r.data;}
function showCredentials(d){if(!d.password)return;$('credentials').hidden=false;$('credentials').textContent=`Zapisz dane logowania:\n${d.name||''}\nLogin: ${d.email||''}\nHasło: ${d.password}\nHasło nie będzie ponownie wyświetlane.`;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('message').textContent='Pracuję…';try{await fn();$('message').textContent='Gotowe.'}catch(e){$('message').textContent=e.message}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function refresh(){data=await call({action:'list'});$('login').hidden=true;$('panel').hidden=false;const old=$('createCounty').value;$('createCounty').innerHTML=data.counties.map(c=>`<option value="${esc(c.id)}">${esc(c.province)} · ${esc(c.name)}</option>`).join('');if(data.counties.some(c=>c.id===old))$('createCounty').value=old;render();}
function render(){const q=$('search').value.toLocaleLowerCase('pl'),role=$('filterRole').value,state=$('filterState').value;const county=id=>data.counties.find(c=>c.id===id);const protectedIds=new Set(data.admins.map(a=>a.user_id));
const rows=data.accounts.filter(a=>(!role||a.role===role)&&(state==='all'||!a.archived_at)&&(state!=='disabled'||!a.enabled)&&[a.unit_name,a.login_email,county(a.county_id)?.name].join(' ').toLocaleLowerCase('pl').includes(q));
$('accounts').innerHTML=rows.map(a=>`<tr><td><b>${esc(a.unit_name)}</b><small>${a.role==='UNIT'?'OSP':esc(a.role)} · ${esc(a.login_email)}</small></td><td>${esc(county(a.county_id)?.name||'—')}</td><td>${a.archived_at?'Usunięte':a.enabled?'Aktywne':'Wyłączone'}${protectedIds.has(a.user_id)?' · administrator':''}</td><td>${a.archived_at||protectedIds.has(a.user_id)?'—':['rename','move','reset_password',a.enabled?'disable':'enable','archive'].map(action=>`<button data-id="${esc(a.user_id)}" data-action="${action}" class="${action==='archive'?'danger':''}">${({rename:'Nazwa',move:'Powiat',reset_password:'Nowe hasło',disable:'Wyłącz',enable:'Włącz',archive:'Usuń'})[action]}</button>`).join('')}</td></tr>`).join('')||'<tr><td colspan="4">Brak kont spełniających kryteria.</td></tr>';
$('counties').innerHTML=data.counties.map(c=>`<p><b>${esc(c.province)} · ${esc(c.name)}</b> — ${data.accounts.filter(a=>a.county_id===c.id&&!a.archived_at).length} kont</p>`).join('');}
$('accounts').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=data.accounts.find(a=>a.user_id===b.dataset.id);if(!a)return;const body={action:b.dataset.action,user_id:a.user_id};
if(body.action==='rename'){body.name=prompt('Nowa nazwa konta:',a.unit_name);if(body.name===null)return;}
else if(body.action==='move'){const options=data.counties.map((c,i)=>`${i+1}. ${c.province} · ${c.name}`).join('\n');const answer=prompt('Podaj numer powiatu:\n'+options);if(answer===null)return;const n=Number(answer);if(!Number.isInteger(n)||n<1||n>data.counties.length){$('message').textContent='Nieprawidłowy numer powiatu.';return}body.county_id=data.counties[n-1].id;}
else if(body.action==='archive'){body.confirmation=prompt(`Trwale wycofać ${a.unit_name}? Historia pozostanie. Aby potwierdzić, wpisz login:\n${a.login_email}`);if(body.confirmation===null)return;}
else if(!confirm(`${b.textContent}: ${a.unit_name}?`))return;
run(async()=>{const d=await call(body);showCredentials({...d,email:a.login_email,name:a.unit_name});await refresh()});};
$('loginForm').onsubmit=e=>{e.preventDefault();run(async()=>{const r=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';if(r.error)throw Error('Nieprawidłowy login lub hasło.');try{await refresh()}catch(e){await sb.auth.signOut();throw e}})};
$('logout').onclick=()=>run(async()=>{await sb.auth.signOut();data={accounts:[],counties:[],admins:[]};$('panel').hidden=true;$('login').hidden=false;$('credentials').textContent='';$('credentials').hidden=true;$('accounts').textContent=''});
$('refresh').onclick=()=>run(refresh);for(const id of ['search','filterRole','filterState'])$(id).oninput=render;
$('createForm').onsubmit=e=>{e.preventDefault();run(async()=>{const d=await call({action:'create_account',name:$('name').value,slug:$('slug').value,role:$('role').value,county_id:$('createCounty').value});showCredentials(d);$('createForm').reset();await refresh()})};
$('adminForm').onsubmit=e=>{e.preventDefault();if(!confirm('Utworzyć dodatkowego administratora wszystkich powiatów i kont?'))return;run(async()=>{showCredentials(await call({action:'create_admin',name:'Administrator FIREMAP',slug:$('adminSlug').value}));$('adminForm').reset();await refresh()})};
const directory=window.firemapAreas;
$('province').innerHTML='<option value="">Wybierz…</option>'+directory.PROVINCES.map(p=>`<option>${esc(p)}</option>`).join('');
$('province').onchange=async()=>{const version=++areaVersion;areas=[];$('areaCounty').disabled=true;$('areaCounty').innerHTML='<option value="">Ładowanie…</option>';try{const rows=await directory.loadCounties($('province').value);if(version!==areaVersion)return;areas=rows;$('areaCounty').innerHTML='<option value="">Wybierz…</option>'+rows.map((r,i)=>`<option value="${i}">${esc(r.name)}</option>`).join('');$('areaCounty').disabled=false}catch{$('message').textContent='Nie pobrano listy powiatów. Wybierz województwo ponownie.'}};
$('countyForm').onsubmit=e=>{e.preventDefault();run(async()=>{const row=areas[Number($('areaCounty').value)];if($('areaCounty').value===''||!row)throw Error('Wybierz powiat.');const area=await directory.resolveArea($('province').value,row);showCredentials(await call({action:'create_county',area,name:$('countyName').value,slug:$('countySlug').value}));await refresh()})};
sb.auth.getSession().then(r=>{if(r.data.session)run(refresh)});
})();
