(()=>{
if(window.__firemapCountyAdmin)return;window.__firemapCountyAdmin=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){
 const ctx=window.firemapSkCtx;if(!ctx?.sb||!window.firemapAreas)return setTimeout(init,250);
 const sb=ctx.sb,{data:session}=await sb.auth.getSession();if(!session.session)return;
 const{data:a}=await sb.from('firemap_accounts').select('role,enabled,county_id').eq('user_id',session.session.user.id).maybeSingle();
 if(a?.role!=='SK'||!a.enabled||!a.county_id||document.getElementById('countyAdmin'))return;
 const{data:county}=await sb.from('firemap_counties').select('name,province').eq('id',a.county_id).maybeSingle();
 const card=document.createElement('details');card.id='countyAdmin';card.className='card';card.innerHTML=`<summary style="font-weight:800;cursor:pointer">Jednostki mojego powiatu</summary><p class="hint">${esc(county?.province)} — ${esc(county?.name)}. Konta jednostek pojawią się na liście logowania tego powiatu.</p><label>Nazwa jednostki<input id="cuName" placeholder="np. OSP Nowa Wieś" maxlength="100"></label><label>Identyfikator konta<input id="cuSlug" placeholder="np. osp-nowa-wies" maxlength="60" autocapitalize="none"></label><label>Rodzaj<select id="cuRole"><option value="UNIT">OSP / jednostka</option><option value="JRG">JRG</option></select></label><label>Hasło<input id="cuPassword" type="password" autocomplete="new-password" placeholder="Puste = wygeneruj silne hasło" maxlength="128"></label><button class="fireBtn" id="cuCreate">Utwórz konto i hasło</button><div id="cuResult" role="status" style="overflow-wrap:anywhere;white-space:pre-wrap;margin-top:10px"></div><button id="cuCopy" class="secondary" hidden>Kopiuj dane logowania</button><div class="sectionLabel">Jednostki i hasła</div><div id="cuList"></div><button class="secondary" id="cuQr">Podłącz zastęp szybko przez QR</button>`;
 document.querySelector('.panel').insertBefore(card,document.getElementById('logout'));
 const css=document.createElement('style');css.textContent='#countyAdmin label,#countyActivation label{display:block;margin-top:8px;font-size:12px;color:#cbd5e1}#countyAdmin select,#countyActivation select{width:100%;min-height:43px;background:#091525;color:white;border:1px solid #475569;border-radius:10px}';document.head.appendChild(css);
 let credentials='';const $=id=>card.querySelector('#'+id);
 async function call(body){const{data,error}=await sb.functions.invoke('manage-county',{body});if(error){let detail;try{detail=await error.context.json()}catch{}throw Error(detail?.error||'Błąd połączenia. Sprawdź listę kont przed ponowną próbą.');}if(data?.error)throw Error(data.error);return data;}
 function showCredentials(name,email,password){credentials=`${name}\nPowiat: ${county?.name}\nLogowanie: ${new URL('login.html',location.href).href}\nKonto: ${email}\nHasło: ${password}`;$('cuResult').textContent=credentials;$('cuCopy').hidden=false;}
 $('cuCopy').onclick=async()=>{try{await navigator.clipboard.writeText(credentials);$('cuCopy').textContent='Skopiowano';}catch{$('cuResult').textContent=credentials+'\nZaznacz i skopiuj dane ręcznie.';}};
 async function list(){const{data,error}=await sb.from('firemap_accounts').select('user_id,unit_name,role,enabled,login_email').eq('county_id',a.county_id).in('role',['UNIT','JRG']).order('unit_name');if(error){$('cuList').textContent='Nie udało się pobrać jednostek.';return;}$('cuList').innerHTML=(data||[]).map(u=>`<div style="padding:8px;border-bottom:1px solid #334155"><b>${esc(u.unit_name)}</b><small style="display:block;overflow-wrap:anywhere">${esc(u.login_email)}</small><button class="secondary" data-reset="${u.user_id}">Wygeneruj nowe hasło</button></div>`).join('')||'<div class="hint">Nie dodano jeszcze jednostek.</div>';
  $('cuList').querySelectorAll('[data-reset]').forEach(b=>b.onclick=async()=>{const u=data.find(x=>x.user_id===b.dataset.reset);if(!confirm('Wygenerować nowe hasło dla '+u.unit_name+'? Dotychczasowe hasło przestanie działać przy kolejnym logowaniu.'))return;b.disabled=true;try{const d=await call({action:'reset_password',user_id:u.user_id});showCredentials(u.unit_name,u.login_email,d.password);}catch(e){$('cuResult').textContent=e.message;}finally{b.disabled=false;}});
 }
 $('cuCreate').onclick=async()=>{const b=$('cuCreate');b.disabled=true;$('cuResult').textContent='Tworzę konto…';try{const d=await call({action:'create_unit',name:$('cuName').value,slug:$('cuSlug').value,role:$('cuRole').value,password:$('cuPassword').value});$('cuPassword').value='';showCredentials(d.name,d.email,d.password);await list();}catch(e){$('cuResult').textContent=e.message;}finally{b.disabled=false;}};
 $('cuQr').onclick=()=>{const q=document.getElementById('fmJoinCodesCard');q?.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('fmJoinIncident')?.focus();};
 await list();
 const{data:permission}=await sb.from('firemap_platform_admins').select('user_id').eq('user_id',session.session.user.id).maybeSingle();if(!permission)return;
 const admin=document.createElement('details');admin.id='countyActivation';admin.className='card';admin.innerHTML='<summary style="font-weight:800;cursor:pointer">Aktywuj SK kolejnego powiatu</summary><p class="hint">Tworzy osobne SK. Nowe konto będzie zarządzało tylko własnym powiatem.</p><label>Województwo<select id="caProvince"></select></label><label>Powiat<select id="caCounty"></select></label><label>Nazwa SK<input id="caName" placeholder="np. KP PSP …"></label><label>Identyfikator powiatu<input id="caSlug" placeholder="np. slaskie-czestochowski" maxlength="60" autocapitalize="none"></label><label>Hasło SK<input id="caPassword" type="password" autocomplete="new-password" placeholder="Puste = wygeneruj silne hasło"></label><button class="fireBtn" id="caCreate">Aktywuj powiat i konto SK</button><div id="caResult" role="status" style="white-space:pre-wrap;overflow-wrap:anywhere;margin-top:10px"></div>';
 card.after(admin);const q=id=>admin.querySelector('#'+id),areas=window.firemapAreas;let rows=[],seq=0;
 q('caProvince').innerHTML='<option value="">Wybierz województwo…</option>'+areas.PROVINCES.map(p=>'<option>'+esc(p)+'</option>').join('');
 q('caProvince').onchange=async()=>{const version=++seq;rows=[];q('caCounty').disabled=true;q('caCounty').innerHTML='<option value="">Ładowanie…</option>';try{const next=await areas.loadCounties(q('caProvince').value);if(version!==seq)return;rows=next;q('caCounty').innerHTML='<option value="">Wybierz powiat…</option>'+rows.map((r,i)=>'<option value="'+i+'">'+esc(r.name)+'</option>').join('');q('caCounty').disabled=false;}catch{q('caResult').textContent='Nie udało się pobrać powiatów. Spróbuj ponownie.';}};
 q('caCreate').onclick=async()=>{const i=q('caCounty').value;if(i===''||!rows[+i]){q('caResult').textContent='Wybierz województwo i powiat.';return;}q('caCreate').disabled=true;q('caResult').textContent='Tworzę SK…';try{const area=await areas.resolveArea(q('caProvince').value,rows[+i]);const d=await call({action:'create_county',area,slug:q('caSlug').value,name:q('caName').value,password:q('caPassword').value});q('caPassword').value='';q('caResult').textContent=`Utworzono ${d.name}\nWybierz SK powiatowe → ${area.province} → ${area.county}\nHasło: ${d.password}\nZapisz i przekaż dane obsadzie SK.`;}catch(e){q('caResult').textContent=e.message;}finally{q('caCreate').disabled=false;}};
}
function wait(){if(!window.firemapSkCtx?.sb)return setTimeout(wait,200);init();window.firemapSkCtx.sb.auth.onAuthStateChange(()=>setTimeout(init,0));}wait();
})();
