/* Acknowledged, incident-scoped attention requests. Never queue an offline alert. */
(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function init(){const c=window.firemapHelpCtx||window.firemapSkCtx||window.firemapCtx;if(!c?.sb||!c.map)return setTimeout(init,300);if(window.__helpStarted)return;window.__helpStarted=true;
const {sb,map}=c,token=c.state?.session_token||null;
const css=document.createElement('style');css.textContent='#fmHelpButton{position:fixed;z-index:940;left:12px;bottom:176px;width:auto;min-height:46px;padding:10px 14px;border:2px solid white;border-radius:12px;background:#9f1239;color:white;font-weight:900;touch-action:none;user-select:none}#fmHelpPanel{position:fixed;z-index:1900;left:12px;right:12px;top:12%;max-height:75vh;overflow:auto;max-width:480px;margin:auto;padding:16px;border:2px solid #fb7185;border-radius:14px;background:#0a1626;color:white}#fmHelpPanel button,#fmHelpPanel select,#fmHelpPanel input{min-height:44px;width:100%;margin:5px 0}#fmHelpPanel section{border-top:1px solid #475569;padding:8px 0}#fmHelpPanel small{display:block}#fmHelpBanner{position:fixed;z-index:935;left:12px;bottom:226px;max-width:260px;background:#9f1239;color:white;padding:8px;border:2px solid white;border-radius:9px;font-weight:bold;cursor:pointer}';document.head.appendChild(css);
const button=document.createElement('button');button.id='fmHelpButton';button.textContent='✋ POMOC';button.title='Przytrzymaj 2 sekundy, aby zgłosić ważny komunikat';button.setAttribute('aria-label',button.title);document.body.appendChild(button);
const banner=document.createElement('button');banner.id='fmHelpBanner';banner.hidden=true;document.body.appendChild(banner);
const panel=document.createElement('div');panel.id='fmHelpPanel';panel.hidden=true;panel.innerHTML='<h2>✋ POMOC / ważny komunikat</h2><p>Sygnał dla uczestników zdarzenia. Po potwierdzeniu skontaktuj się przez radio lub telefon.</p><label>Zdarzenie<select id="helpIncident"></select></label><label>Krótki komunikat (opcjonalnie)<input id="helpMessage" maxlength="160" placeholder="np. pilny kontakt z KDR"></label><button id="helpSend">Potwierdzam — wyślij POMOC</button><p id="helpStatus" role="status"></p><div id="helpRows"></div><button id="helpClose">Zamknij</button>';document.body.appendChild(panel);
const $=id=>panel.querySelector('#'+id);let timer=null,armed=false,busy=false,polling=false,lastHtml='',markers=new Map();
function cancel(){clearTimeout(timer);timer=null;button.textContent='✋ POMOC';}
async function open(ready){armed=ready;panel.hidden=false;$('helpSend').disabled=!armed;$('helpStatus').textContent=ready?'Sprawdź zdarzenie i potwierdź wysłanie.':'Aby zgłosić POMOC, przytrzymaj przycisk 2 sekundy.';try{const {data,error}=await (c.readSb||sb).from('incidents').select('id,description').eq('active',true);if(error)throw error;const rows=token?(data||[]).filter(i=>i.id===c.state.incident_id):(data||[]);$('helpIncident').innerHTML=rows.map(i=>`<option value="${esc(i.id)}">${esc(i.description||'Zdarzenie')}</option>`).join('');const assigned=token?c.state.incident_id:localStorage.getItem('firemapIncidentId');if(rows.some(i=>i.id===assigned))$('helpIncident').value=assigned;else if(!window.firemapSkCtx)$('helpIncident').value='';}catch(e){$('helpStatus').textContent='Nie pobrano zdarzeń: '+e.message;$('helpSend').disabled=true}}
function hold(){if(busy||timer)return;button.textContent='Przytrzymaj…';timer=setTimeout(()=>{cancel();open(true)},2000)}
button.addEventListener('pointerdown',e=>{if(e.button!==0)return;hold()});['pointerup','pointercancel','pointerleave'].forEach(n=>button.addEventListener(n,cancel));button.addEventListener('keydown',e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();hold()}});button.addEventListener('keyup',cancel);button.addEventListener('blur',cancel);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancel();armed=false;$('helpSend').disabled=true}});banner.onclick=()=>open(false);$('helpClose').onclick=()=>{armed=false;panel.hidden=true};
$('helpSend').onclick=async()=>{if(!armed||busy)return;const id=$('helpIncident').value;if(!id)return $('helpStatus').textContent='Wybierz zdarzenie.';if(!navigator.onLine)return $('helpStatus').textContent='OFFLINE — POMOC NIE ZOSTAŁA WYSŁANA. Użyj radia lub telefonu.';busy=true;$('helpSend').disabled=true;$('helpStatus').textContent='Wysyłanie…';try{const {error}=await sb.rpc('firemap_help_raise',{p_incident_id:id,p_message:$('helpMessage').value.trim(),p_session_token:token});if(error)throw error;armed=false;$('helpStatus').textContent='Serwer potwierdził zgłoszenie. Uczestnicy z połączeniem zobaczą POMOC.';await refresh()}catch(e){armed=false;$('helpStatus').textContent='Brak potwierdzenia wysłania. Sprawdź listę zgłoszeń; użyj radia lub telefonu. '+(e.message||'')}finally{busy=false}};
async function refresh(){if(polling||!navigator.onLine){if(!navigator.onLine){banner.hidden=false;banner.textContent='✋ POMOC: brak połączenia — stan nieaktualny'}return}polling=true;try{const {data,error}=await sb.rpc('firemap_help_read',{p_session_token:token});if(error)throw error;const rows=Array.isArray(data)?data:[];banner.hidden=!rows.length;banner.textContent='✋ POMOC: '+rows.length+' · '+(rows[0]?.sender_label||'');const html=rows.map(r=>`<section><b>✋ ${esc(r.sender_label)}</b><small>${esc(r.incident_description)} · ${new Date(r.created_at).toLocaleTimeString()}</small><p>${esc(r.message||'Prośba o pilny kontakt')}</p><button data-focus="${esc(r.id)}">Pokaż miejsce zgłoszenia</button>${r.can_clear?`<button data-clear="${esc(r.id)}">Odwołaj zgłoszenie</button>`:''}</section>`).join('')||'<p>Brak aktywnych zgłoszeń.</p>';if(html!==lastHtml){$('helpRows').innerHTML=html;lastHtml=html;$('helpRows').querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.focus);if(r?.lat!=null&&r?.lng!=null){map.flyTo([r.lat,r.lng],16);panel.hidden=true}});$('helpRows').querySelectorAll('[data-clear]').forEach(b=>b.onclick=async()=>{if(!confirm('Odwołać to zgłoszenie POMOCY?'))return;b.disabled=true;const {error}=await sb.rpc('firemap_help_clear',{p_request_id:b.dataset.clear,p_session_token:token});if(error){$('helpStatus').textContent=error.message;b.disabled=false}else refresh()})}const keep=new Set(rows.map(r=>r.id));for(const[id,m]of markers)if(!keep.has(id)){map.removeLayer(m);markers.delete(id)}for(const r of rows){if(r.lat==null||r.lng==null)continue;let m=markers.get(r.id);if(!m){m=L.marker([r.lat,r.lng],{zIndexOffset:3000,icon:L.divIcon({className:'',html:'<div style="border:3px solid white;background:#9f1239;color:white;border-radius:50%;font-size:24px;width:42px;height:42px;display:grid;place-items:center">✋</div>',iconSize:[42,42],iconAnchor:[21,21]})}).addTo(map);markers.set(r.id,m)}m.bindPopup(`<b>✋ POMOC · ${esc(r.sender_label)}</b><br>${esc(r.message||'Pilny kontakt')}<br><small>Miejsce zgłoszenia · ${new Date(r.created_at).toLocaleString()}</small>`)}}
catch(e){banner.hidden=false;banner.textContent='✋ POMOC: brak aktualizacji';}finally{polling=false}}
setInterval(()=>{if(!document.hidden)refresh()},3000);window.addEventListener('online',refresh);window.addEventListener('offline',refresh);window.addEventListener('focus',refresh);refresh();
}init();})();
