/* Shared operational symbols for SK, authenticated terminals and QR terminals. */
(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={BASE:{label:'W bazie',color:'#64748b'},DISPATCHED:{label:'Wyjazd do akcji',color:'#f59e0b'},ON_SCENE:{label:'Na miejscu',color:'#dc2626'},RETURNING:{label:'Zakończenie działań',color:'#2563eb'}};
function glyph(type){const t=String(type||'').trim().toUpperCase();if(t==='KDR')return'⭐';if(t.includes('QUAD'))return'🏍️';if(t==='SD'||t.startsWith('SD '))return'🪜';if(t==='SLOP')return'🚗';if(t.startsWith('SL'))return'🚐';if(t.includes('MIKROBUS'))return'🚌';if(t.includes('PRZYCZEPA'))return'◫';if(['GBA','GCBA','GBM','GLM'].some(x=>t.startsWith(x)))return'🚒';return'🚙'}
function forceBadge(v){const g=v.force_group||String(v.unit_name||'').split('|')[0].trim();if(!['WOO','COO','EXTERNAL'].includes(g))return '';return `<span class="fm-symbol-force" style="background:${g==='WOO'?'#7c3aed':g==='COO'?'#2563eb':'#475569'}">${g==='EXTERNAL'?'ZEWN':g}${v.specialist_group?' ★':''}</span>`}
function vehicle(v,{stale=false,own=false}={}){const kdr=String(v.vehicle_type||'').trim().toUpperCase()==='KDR',s=statuses[v.status]||statuses.BASE;return L.divIcon({className:'',html:`<div class="fm-symbol${stale?' fm-symbol-stale':''}${own?' fm-symbol-own':''}" title="${esc(kdr?'KDR':v.vehicle_type)} · ${esc(stale?'Ostatnia znana pozycja':s.label)}" style="background:${stale?'#64748b':kdr?'#ca8a04':s.color};border-radius:${kdr?'50%':'13px'}">${glyph(v.vehicle_type)}${kdr?'':forceBadge(v)}${own?`<span class="fm-symbol-label">${esc(v.call_sign)} · TY</span>`:''}${stale?'<span class="fm-symbol-warning">!</span>':''}</div>`,iconSize:[42,42],iconAnchor:[21,21]})}
function incident(kind){return L.divIcon({className:'',html:`<div class="fm-symbol" style="background:${kind==='FIRE'?'#dc2626':'#d97706'}" title="${kind==='FIRE'?'Pożar':'Miejscowe zagrożenie'}">${kind==='FIRE'?'🔥':'⚠️'}</div>`,iconSize:[42,42],iconAnchor:[21,21]})}
window.firemapSymbols={glyph,vehicle,incident,statuses};
const css=document.createElement('style');css.textContent='.fm-symbol{box-sizing:border-box;width:42px;height:42px;position:relative;border:3px solid white;border-radius:13px;display:grid;place-items:center;font-size:20px;line-height:1;box-shadow:0 3px 12px #0008}.fm-symbol-stale{border-style:dashed;opacity:.8}.fm-symbol-label{position:absolute;bottom:44px;left:50%;transform:translateX(-50%);white-space:nowrap;font:700 10px system-ui;background:#07111fe8;color:white;padding:3px 5px;border:1px solid white;border-radius:5px}.fm-symbol-force{position:absolute;top:34px;left:50%;transform:translateX(-50%);border:1px solid white;border-radius:5px;color:white;padding:2px 4px;font:700 9px system-ui;white-space:nowrap}.fm-symbol-warning{position:absolute;right:-6px;top:-9px;border:1px solid #facc15;background:#111827;color:#facc15;border-radius:50%;width:20px;height:20px;display:grid;place-items:center;font:700 12px system-ui}';document.head.appendChild(css);
})();
