(async()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=L.map('map',{minZoom:3,preferCanvas:true}).setView([52,19],7);map.attributionControl.addAttribution('© OpenStreetMap contributors · ODbL');let base=L.layerGroup().addTo(map),pack=null,position=null,rows=[];
window.firemapCtx={map,sb:{from(table){let filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},in(){return q},order(){return q},then(resolve){let data=pack?(table==='incidents'?[{...pack.incident,active:true}]:pack.drawings):[];for(const[k,v]of filters)data=data.filter(x=>x[k]===v);resolve({data,error:null})}};return q},channel(){return{on(){return this},subscribe(){}}}}};
async function list(){rows=await window.firemapOfflineStore.all();$('packs').replaceChildren(...rows.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;return o}));$('state').textContent=rows.length?'Wybierz zapisany obszar.':'Brak ważnych pakietów dla ostatniego użytkownika. Pobierz obszar w terminalu online.'}
function show(){pack=rows.find(p=>p.id===$('packs').value);if(!pack)return;base.clearLayers();map.fitBounds(pack.bounds);L.rectangle(pack.bounds,{color:'#d97706',weight:2,fill:false}).addTo(base);for(const e of pack.osm.elements){const t=e.tags||{},pts=e.geometry?.map(p=>[p.lat,p.lon]);let l;if(pts?.length>1){const closed=pts.length>3&&pts[0][0]===pts.at(-1)[0]&&pts[0][1]===pts.at(-1)[1],water=!!t.waterway||t.natural==='water',forest=t.landuse==='forest'||t.natural==='wood';l=closed&&!t.highway?L.polygon(pts,{color:t.building?'#78716c':water?'#38bdf8':forest?'#65a30d':'#a8a29e',weight:1,fillOpacity:.4}):L.polyline(pts,{color:water?'#38bdf8':t.highway==='motorway'?'#d97706':t.highway==='path'||t.highway==='track'?'#a16207':'#57534e',weight:water?2:3})}else if(e.lat!=null&&e.lon!=null){l=L.circleMarker([e.lat,e.lon],{radius:t.emergency?4:2,color:t.emergency?'#2563eb':'#444'});if(t.name)l.bindTooltip(esc(t.name),{permanent:true})}if(l){l.addTo(base);if(t.name)l.bindPopup(esc(t.name))}}$('state').textContent='Zapis: '+new Date(pack.createdAt).toLocaleString()+' · '+pack.drawings.length+' elementów TAKTYKI. Pozycje i zgłoszenia nie są aktualizowane.';window.dispatchEvent(new Event('firemap:tactical:change'))}
$('open').onclick=show;$('del').onclick=async()=>{if(!confirm('Usunąć wybrany pakiet z tego urządzenia?'))return;await window.firemapOfflineStore.remove($('packs').value);pack=null;base.clearLayers();await list();window.dispatchEvent(new Event('firemap:tactical:change'))};$('gps').onclick=()=>navigator.geolocation.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];if(!position)position=L.circleMarker(ll,{radius:8,color:'#2563eb'}).addTo(map);else position.setLatLng(ll);map.setView(ll,16)},()=>{$('state').textContent='Nie udało się ustalić pozycji GPS.'},{enableHighAccuracy:true,timeout:15000});
await list();if(rows.length)show();for(const src of ['tactical-shared-viewer.js','tactical-water-distance.js']){const s=document.createElement('script');s.src=src+'?v=20260918-android-1';s.async=false;document.head.appendChild(s)}
})();
