(()=>{
async function init(){
 const ctx=window.firemapSkCtx;if(!ctx?.account||!window.firemapAreas)return setTimeout(init,250);
 if(ctx.account.role!=='SZTAB'||document.getElementById('rapidHq'))return;
 const {sb,map}=ctx,areas=window.firemapAreas,card=document.createElement('section');card.id='rapidHq';card.className='card';
 card.innerHTML='<h3>Uruchom akcję SZTABU</h3><p class="hint">Wybierz teren i czas dostępu. Zastępy dołączą jednym kodem i będą współdzielić mapę oraz TAKTYKĘ.</p><label>Nazwa akcji<input id="hqName" maxlength="200" placeholder="np. Pożar lasu — rejon północny"></label><label>Województwo<select id="hqProvince"></select></label><label>Powiat akcji<select id="hqCounty"></select></label><label>Dostęp zastępów<select id="hqDays"><option value="1">24 godziny</option><option value="3">3 dni</option><option value="7" selected>7 dni</option><option value="14">14 dni</option><option value="30">30 dni</option></select></label><p class="hint">Czas liczony od wygenerowania kodu. Wszystkie zastępy mają dostęp do wskazanego terminu; zakończenie akcji odbiera go wcześniej. Powiat ustawia widok, nie granice pracy.</p><button class="fireBtn" id="hqStart">URUCHOM AKCJĘ I POKAŻ QR</button><div id="hqState" role="status"></div><button class="secondary" id="hqShowAll">Pokaż wszystkie zastępy</button>';
 document.querySelector('.panel').prepend(card);const $=id=>card.querySelector('#'+id);let counties=[],seq=0;
 for(const p of areas.PROVINCES)$('hqProvince').add(new Option(p,p));
 const style=document.createElement('style');style.textContent='#rapidHq label{display:block;margin-top:9px}#rapidHq select,#rapidHq input{width:100%;min-height:44px;background:#111e30;color:#fff;border:1px solid #475569;border-radius:9px}#hqState{white-space:pre-wrap;overflow-wrap:anywhere;margin:10px 0}';document.head.appendChild(style);
 const {data:ops,error}=await sb.from('incidents').select('id,description,operation_area').eq('rapid_hq',true).eq('active',true);
 if(error){$('hqState').textContent='Nie udało się pobrać akcji. Odśwież stronę.';return}
 const op=ops?.[0];if(op){$('hqName').value=op.description;applyArea(op.operation_area);$('hqStart').textContent='WYGENERUJ NOWY KOD DO TEJ AKCJI';$('hqProvince').value=op.operation_area.province;}
 async function load(){const version=++seq;$('hqCounty').disabled=true;$('hqStart').disabled=true;counties=[];$('hqCounty').replaceChildren(new Option('Ładowanie…',''));try{const rows=await areas.loadCounties($('hqProvince').value);if(version!==seq)return;counties=rows;$('hqCounty').replaceChildren(new Option('Wybierz powiat…',''));rows.forEach((r,i)=>$('hqCounty').add(new Option(r.name,String(i))));if(op){const i=rows.findIndex(r=>r.name===op.operation_area.county);if(i>=0)$('hqCounty').value=String(i);}$('hqCounty').disabled=false;$('hqStart').disabled=false;}catch{if(version===seq)$('hqState').textContent='Nie udało się pobrać powiatów. Wybierz województwo ponownie.'}}
 function applyArea(area){if(!area?.bounds)return;localStorage.setItem('firemapSkDefaultArea',JSON.stringify(area));window.dispatchEvent(new CustomEvent('firemapSkAreaChanged',{detail:area}));map.fitBounds(area.bounds);}
 $('hqProvince').onchange=load;load();
 $('hqStart').onclick=async()=>{const ix=$('hqCounty').value;if(ix===''||!counties[+ix]){$('hqState').textContent='Wybierz powiat akcji.';return}$('hqStart').disabled=true;try{const area=await areas.resolveArea($('hqProvince').value,counties[+ix]);const {data,error}=await sb.rpc('start_hq_operation',{p_name:$('hqName').value.trim(),p_area:area,p_days:Number($('hqDays').value)});if(error)throw error;applyArea(data.area);$('hqState').textContent='Akcja uruchomiona. Kod: '+data.code+'\nDostęp do: '+new Date(data.expires_at).toLocaleString('pl-PL');window.dispatchEvent(new CustomEvent('firemap:hq-code',{detail:data}));}catch(e){$('hqState').textContent=e.message||'Nie udało się uruchomić akcji.'}finally{$('hqStart').disabled=false}};
 $('hqShowAll').onclick=async()=>{const{data,error}=await sb.from('vehicles').select('lat,lng').neq('status','BASE');if(error){$('hqState').textContent='Nie udało się pobrać pozycji.';return}const points=(data||[]).filter(v=>Number.isFinite(v.lat)&&Number.isFinite(v.lng)).map(v=>[v.lat,v.lng]);if(points.length)map.fitBounds(points,{padding:[50,50],maxZoom:15});else $('hqState').textContent='Zastępy nie przesłały jeszcze pozycji.'};
}
init();
})();
