/* FIREMAP tactical layer v1 — shared KDR/SK drawings */
window.FiremapTactical=function({map,sb,userId,canEdit=false,getIncidents=()=>[],onMessage=()=>{}}){
  const layers=new Map();
  let rows=[],selectedIncidentId='',category='SECTOR',mode='',draft=[],preview=null,freehand=false,editingId=null;
  const COLORS={SECTOR:'#2563eb',WATER:'#06b6d4',DANGER:'#dc2626',FIRE_SPREAD:'#f97316',FREEHAND:'#a855f7'};
  const LABELS={SECTOR:'Odcinek bojowy',WATER:'Zaopatrzenie wodne',DANGER:'Strefa niebezpieczna',FIRE_SPREAD:'Kierunek pożaru',FREEHAND:'Notatka KDR'};
  const styleFor=c=>({color:COLORS[c]||COLORS.FREEHAND,weight:c==='DANGER'?4:5,dashArray:c==='DANGER'?'10,7':null,fillColor:COLORS[c]||COLORS.FREEHAND,fillOpacity:c==='DANGER'?.14:.08});
  function clearPreview(){if(preview){map.removeLayer(preview);preview=null}}
  function activeIncident(){const inc=getIncidents()||[];return inc.find(x=>x.id===selectedIncidentId)||inc[0]||null}
  function setIncident(id){selectedIncidentId=id||''}
  function latlngsToCoords(ll){if(Array.isArray(ll)&&ll.length&&Array.isArray(ll[0]))return ll.map(latlngsToCoords);return [ll.lng,ll.lat]}
  function coordsToLatlngs(c){if(Array.isArray(c)&&c.length&&Array.isArray(c[0])&&Array.isArray(c[0][0]))return c.map(coordsToLatlngs);if(Array.isArray(c)&&c.length&&Array.isArray(c[0]))return c.map(x=>[x[1],x[0]]);return [c[1],c[0]]}
  function geometryFromLayer(layer,type){if(type==='CIRCLE'){const p=layer.getLatLng();return{center:[p.lng,p.lat],radius:layer.getRadius()}}return{coordinates:latlngsToCoords(layer.getLatLngs())}}
  function renderRow(r){let layer,s={...styleFor(r.category),...(r.style||{})},g=r.geometry||{};try{if(r.geometry_type==='CIRCLE')layer=L.circle([g.center[1],g.center[0]],{...s,radius:g.radius});else if(r.geometry_type==='POLYGON')layer=L.polygon(coordsToLatlngs(g.coordinates),s);else layer=L.polyline(coordsToLatlngs(g.coordinates),s);layer.addTo(map);layer.bindTooltip((r.label||LABELS[r.category]||'Taktyka'),{sticky:true});layer._firemapDrawingId=r.id;layer.on('click',()=>{if(canEdit&&r.created_by===userId){editingId=r.id;onMessage('Wybrano rysunek. Użyj „Edytuj” lub „Usuń”.')}});layers.set(r.id,layer)}catch(e){console.warn('drawing render',e)}}
  async function refresh(){const ids=(getIncidents()||[]).map(x=>x.id);if(!ids.length){for(const l of layers.values())map.removeLayer(l);layers.clear();rows=[];return}const {data,error}=await sb.from('incident_drawings').select('*').in('incident_id',ids).order('created_at');if(error){if(error.code!=='42P01')console.warn(error);return}rows=data||[];const seen=new Set(rows.map(r=>r.id));for(const[id,l]of layers)if(!seen.has(id)){map.removeLayer(l);layers.delete(id)}for(const r of rows){const old=layers.get(r.id);if(old){map.removeLayer(old);layers.delete(r.id)}renderRow(r)}}
  async function save(type,geometry,label=''){const inc=activeIncident();if(!inc)return onMessage('Brak aktywnego zdarzenia do przypisania rysunku.');const payload={incident_id:inc.id,category,geometry_type:type,geometry,style:styleFor(category),label:label||LABELS[category],created_by:userId};const {error}=await sb.from('incident_drawings').insert(payload);if(error)return onMessage('Nie zapisano rysunku: '+error.message);draft=[];clearPreview();mode='';await refresh();onMessage('Rysunek taktyczny zapisany.')}
  function begin(newMode,newCategory){if(!canEdit)return onMessage('Rysować może terminal pracujący jako KDR.');if(!activeIncident())return onMessage('Brak aktywnego zdarzenia.');mode=newMode;category=newCategory||category;draft=[];clearPreview();freehand=false;map.dragging.enable();onMessage(newMode==='FREEHAND'?'Przeciągnij palcem po mapie, aby rysować.':'Dotykaj mapy, aby wskazywać kolejne punkty. Zakończ przyciskiem ✓.')}
  function onClick(e){if(!canEdit||!mode||mode==='FREEHAND')return;draft.push([e.latlng.lat,e.latlng.lng]);clearPreview();const s=styleFor(category);if(mode==='CIRCLE'&&draft.length>=2){const radius=map.distance(draft[0],draft[draft.length-1]);preview=L.circle(draft[0],{...s,radius}).addTo(map)}else if(mode==='POLYGON')preview=L.polygon(draft,s).addTo(map);else preview=L.polyline(draft,s).addTo(map)}
  function pointerStart(e){if(!canEdit||mode!=='FREEHAND')return;freehand=true;draft=[];map.dragging.disable();const oe=e.originalEvent||e,pt=oe.touches?.[0]||oe;const ll=map.containerPointToLatLng(L.point(pt.clientX-map.getContainer().getBoundingClientRect().left,pt.clientY-map.getContainer().getBoundingClientRect().top));draft.push([ll.lat,ll.lng]);clearPreview();preview=L.polyline(draft,styleFor(category)).addTo(map)}
  function pointerMove(ev){if(!freehand||mode!=='FREEHAND')return;ev.preventDefault();const rect=map.getContainer().getBoundingClientRect(),p=ev.touches?.[0]||ev,ll=map.containerPointToLatLng([p.clientX-rect.left,p.clientY-rect.top]);const last=draft[draft.length-1];if(!last||map.distance(last,[ll.lat,ll.lng])>2){draft.push([ll.lat,ll.lng]);preview.setLatLngs(draft)}}
  function pointerEnd(){if(!freehand)return;freehand=false;map.dragging.enable();if(draft.length>1)finish()}
  async function finish(){if(!mode)return;if(mode==='CIRCLE'){if(draft.length<2)return onMessage('Wskaż środek i promień okręgu.');const center=draft[0],radius=map.distance(draft[0],draft[draft.length-1]);return save('CIRCLE',{center:[center[1],center[0]],radius})}if(mode==='POLYGON'){if(draft.length<3)return onMessage('Strefa wymaga co najmniej 3 punktów.');return save('POLYGON',{coordinates:[draft.map(p=>[p[1],p[0]])]})}if(draft.length<2)return onMessage('Linia wymaga co najmniej 2 punktów.');return save(mode==='FREEHAND'?'FREEHAND':'POLYLINE',{coordinates:draft.map(p=>[p[1],p[0]])})}
  function cancel(){mode='';draft=[];freehand=false;map.dragging.enable();clearPreview();onMessage('Rysowanie anulowane.')}
  async function removeSelected(){if(!editingId)return onMessage('Najpierw dotknij swojego rysunku na mapie.');const row=rows.find(r=>r.id===editingId);if(!row||row.created_by!==userId)return onMessage('Możesz usuwać tylko swoje rysunki.');const {error}=await sb.from('incident_drawings').delete().eq('id',editingId);if(error)return onMessage(error.message);editingId=null;await refresh();onMessage('Rysunek usunięty.')}
  async function clearMine(){const inc=activeIncident();if(!inc)return;const {error}=await sb.from('incident_drawings').delete().eq('incident_id',inc.id).eq('created_by',userId);if(error)return onMessage(error.message);await refresh();onMessage('Twoje rysunki dla tego zdarzenia zostały wyczyszczone.')}
  function enableEdit(){if(!editingId)return onMessage('Najpierw dotknij swojego rysunku.');const l=layers.get(editingId);if(!l)return;if(l.editing?.enable){l.editing.enable();onMessage('Przesuń punkty rysunku, potem wybierz „Zapisz edycję”.')}else onMessage('Ten typ rysunku nie obsługuje edycji punktów w tej wersji.')}
  async function saveEdit(){if(!editingId)return;const l=layers.get(editingId),row=rows.find(r=>r.id===editingId);if(!l||!row)return;const geometry=geometryFromLayer(l,row.geometry_type);const {error}=await sb.from('incident_drawings').update({geometry}).eq('id',editingId);if(error)return onMessage(error.message);l.editing?.disable?.();editingId=null;await refresh();onMessage('Edycja zapisana.')}
  map.on('click',onClick);const c=map.getContainer();c.addEventListener('pointerdown',pointerStart,{passive:false});c.addEventListener('pointermove',pointerMove,{passive:false});c.addEventListener('pointerup',pointerEnd,{passive:false});c.addEventListener('pointercancel',pointerEnd,{passive:false});
  const channel=sb.channel('firemap-tactical-'+Math.random()).on('postgres_changes',{event:'*',schema:'public',table:'incident_drawings'},refresh).subscribe();
  return{refresh,setIncident,begin,finish,cancel,removeSelected,clearMine,enableEdit,saveEdit,setCanEdit(v){canEdit=!!v},destroy(){sb.removeChannel(channel)}};
};