(()=>{
const wait=()=>{
  const ctx=window.firemapCtx;
  if(!ctx?.map||!ctx?.sb||!ctx?.session){setTimeout(wait,250);return}
  init(ctx);
};
function init({map,sb,session}){
  const $=id=>document.getElementById(id);
  const root=document.body;
  const css=document.createElement('style');
  css.textContent=`
  .kdr-main-btn,.tactical-main-btn{position:fixed;z-index:910;left:12px;border:1px solid #ffffff33;color:#fff;font-weight:900;border-radius:13px;padding:10px 12px;box-shadow:0 8px 24px #0008;backdrop-filter:blur(14px)}
  .kdr-main-btn{top:82px;background:#8a6408e8}.kdr-main-btn.active{background:#ca8a04;outline:2px solid #fde68a}.tactical-main-btn{top:132px;background:#7c3aedee;display:none}.tactical-main-btn.show{display:block}
  .tactical-sheet{position:fixed;z-index:1250;left:50%;bottom:0;transform:translate(-50%,105%);width:min(580px,100%);max-height:82vh;overflow:auto;background:#0a1626;border:1px solid #475569;border-radius:22px 22px 0 0;padding:16px 16px max(18px,env(safe-area-inset-bottom));transition:.2s;box-shadow:0 -20px 50px #0009;color:#fff}.tactical-sheet.open{transform:translate(-50%,0)}
  .tactical-sheet h2{margin:0 0 5px}.tactical-sheet p{font-size:12px;color:#cbd5e1}.tactical-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tac-btn{min-height:52px;border:1px solid #475569;border-radius:12px;background:#1e293b;color:#fff;font-weight:900}.tac-btn.active{outline:2px solid white}.tac-danger{background:#991b1b}.tac-water{background:#1d4ed8}.tac-sector{background:#334155}.tac-fire{background:#c2410c}.tac-free{background:#6d28d9}.tac-edit{background:#0f766e}.tac-clear{background:#7f1d1d}.tac-close{width:100%;min-height:46px;margin-top:10px;background:#334155;color:#fff;border:0;border-radius:11px;font-weight:900}.tac-select{width:100%;height:44px;background:#111e30;color:white;border:1px solid #475569;border-radius:10px;padding:0 8px}.tac-note{font-size:11px;color:#94a3b8;margin-top:8px}.tac-selected{filter:drop-shadow(0 0 5px #fff)}
  @media(max-width:560px){.kdr-main-btn,.tactical-main-btn{left:10px;font-size:12px;padding:9px 10px}.kdr-main-btn{top:74px}.tactical-main-btn{top:120px}}
  `;root.appendChild(css);
  const kdr=document.createElement('button');kdr.id='kdrMainBtn';kdr.className='kdr-main-btn';kdr.textContent='⭐ KDR';root.appendChild(kdr);
  const tac=document.createElement('button');tac.id='tacticalMainBtn';tac.className='tactical-main-btn';tac.textContent='✏️ TAKTYKA';root.appendChild(tac);
  const sheet=document.createElement('div');sheet.id='tacticalSheet';sheet.className='tactical-sheet';sheet.innerHTML=`<h2>✏️ Taktyka KDR</h2><p>Wspólna warstwa wybranego aktywnego zdarzenia. Rysunki widzą SK i wszystkie zalogowane zastępy.</p><label>Aktywne zdarzenie</label><select id="tacticalIncident" class="tac-select"></select><div class="tactical-grid" style="margin-top:10px"><button class="tac-btn tac-sector" data-tac="SECTOR">⬡ Odcinek bojowy</button><button class="tac-btn tac-water" data-tac="WATER">💧 Zaopatrzenie wodne</button><button class="tac-btn tac-danger" data-tac="DANGER">⭕ Strefa niebezpieczna</button><button class="tac-btn tac-fire" data-tac="FIRE_SPREAD">➡️ Kierunek pożaru</button><button class="tac-btn tac-free" data-tac="FREEHAND">✏️ Odręcznie</button><button class="tac-btn tac-edit" id="tacEdit">✥ Edycja</button><button class="tac-btn" id="tacDelete">🗑 Usuń zaznaczony</button><button class="tac-btn tac-clear" id="tacClear">🧹 Wyczyść warstwę</button></div><div class="tac-note" id="tacState">Wybierz zdarzenie i narzędzie. Kliknięcie istniejącego rysunku zaznacza go.</div><button class="tac-close" id="tacClose">Zamknij</button>`;root.appendChild(sheet);

  let kdrMode=localStorage.getItem('firemapKdrMode')==='1',activeIncident=null,mode=null,startPoint=null,temp=null,selectedId=null,editMode=false,freePts=[],freeActive=false;
  const layers=new Map();
  const styles={SECTOR:{color:'#facc15',weight:4,fillColor:'#facc15',fillOpacity:.08},WATER:{color:'#2563eb',weight:5,dashArray:'10,6'},DANGER:{color:'#dc2626',weight:4,fillColor:'#dc2626',fillOpacity:.12},FIRE_SPREAD:{color:'#f97316',weight:5,dashArray:'8,5'},FREEHAND:{color:'#a855f7',weight:4}};
  function syncMode(){kdrMode=localStorage.getItem('firemapKdrMode')==='1';kdr.classList.toggle('active',kdrMode);tac.classList.toggle('show',kdrMode);if(!kdrMode)sheet.classList.remove('open')}
  setInterval(syncMode,600);syncMode();
  kdr.onclick=()=>{const status=$('statusSheet');if(status)status.classList.add('open');else alert('Panel KDR chwilowo niedostępny. Odśwież aplikację.')};
  tac.onclick=async()=>{if(!kdrMode)return;sheet.classList.add('open');await refreshIncidents();await refreshDrawings()};
  $('tacClose').onclick=()=>{sheet.classList.remove('open');stopDraw()};
  async function refreshIncidents(){const {data}=await sb.from('incidents').select('id,kind,description,lat,lng').eq('active',true).order('created_at',{ascending:false});const sel=$('tacticalIncident');sel.innerHTML=(data||[]).map(i=>`<option value="${i.id}">${i.kind==='FIRE'?'🔥':'⚠️'} ${escapeHtml(i.description||'Zdarzenie')}</option>`).join('');activeIncident=sel.value||null;sel.onchange=()=>{activeIncident=sel.value;refreshDrawings()};if(!activeIncident)$('tacState').textContent='Brak aktywnego zdarzenia — SK musi najpierw dodać zdarzenie.'}
  function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function stopDraw(){mode=null;startPoint=null;freeActive=false;freePts=[];if(temp){map.removeLayer(temp);temp=null}map.dragging.enable();document.querySelectorAll('[data-tac]').forEach(b=>b.classList.remove('active'))}
  document.querySelectorAll('[data-tac]').forEach(b=>b.onclick=()=>{if(!activeIncident)return $('tacState').textContent='Najpierw wybierz aktywne zdarzenie.';stopDraw();mode=b.dataset.tac;b.classList.add('active');$('tacState').textContent=mode==='FREEHAND'?'Przytrzymaj palec/mysz i rysuj po mapie.':mode==='DANGER'?'Kliknij środek, potem punkt na krawędzi koła.':mode==='SECTOR'?'Klikaj wierzchołki obszaru; kliknij pierwszy punkt ponownie, aby zakończyć.':'Klikaj kolejne punkty; dwuklik kończy linię.'});
  function pointArr(ll){return[+ll.lat,+ll.lng]}
  function renderDrawing(d){let st={...(styles[d.category]||{}),...(d.style||{})},g=d.geometry||{},layer;if(d.geometry_type==='CIRCLE'){layer=L.circle(g.center,{...st,radius:g.radius})}else if(d.geometry_type==='POLYGON'){layer=L.polygon(g.points||[],st)}else layer=L.polyline(g.points||[],st);layer.addTo(map);layer._drawing=d;layer.on('click',()=>{selectedId=d.id;layers.forEach((l,id)=>l.getElement?.()?.classList.toggle('tac-selected',id===selectedId));$('tacState').textContent=`Zaznaczono: ${d.label||d.category}`;if(editMode&&d.created_by===session.user.id&&layer.editing)layer.editing.enable()});layers.set(d.id,layer);return layer}
  async function refreshDrawings(){layers.forEach(l=>map.removeLayer(l));layers.clear();if(!activeIncident)return;const {data,error}=await sb.from('incident_drawings').select('*').eq('incident_id',activeIncident).order('created_at');if(error){$('tacState').textContent='Błąd odczytu warstwy taktycznej: '+error.message;return}(data||[]).forEach(renderDrawing)}
  async function save(category,geometry_type,geometry,label){const {error}=await sb.from('incident_drawings').insert({incident_id:activeIncident,category,geometry_type,geometry,style:styles[category]||{},label,created_by:session.user.id});if(error){$('tacState').textContent='Nie zapisano: '+error.message;return}stopDraw();await refreshDrawings();$('tacState').textContent='Rysunek zapisany i udostępniony.'}
  function near(a,b){return map.distance(a,b)<18}
  let clickPts=[];
  map.on('click',e=>{if(!kdrMode||!sheet.classList.contains('open')||!mode||mode==='FREEHAND')return;if(mode==='DANGER'){if(!startPoint){startPoint=e.latlng;temp=L.circle(startPoint,{...styles.DANGER,radius:5}).addTo(map)}else{const r=map.distance(startPoint,e.latlng);save('DANGER','CIRCLE',{center:pointArr(startPoint),radius:r},'Strefa niebezpieczna');startPoint=null}return}if(!clickPts.length)clickPts=[e.latlng];else clickPts.push(e.latlng);if(temp)map.removeLayer(temp);temp=(mode==='SECTOR'?L.polygon(clickPts,styles[mode]):L.polyline(clickPts,styles[mode])).addTo(map);if(mode==='SECTOR'&&clickPts.length>=3&&near(clickPts[0],e.latlng)){const pts=clickPts.map(pointArr);clickPts=[];save('SECTOR','POLYGON',{points:pts},'Odcinek bojowy')}});
  map.on('dblclick',e=>{if(!mode||!['WATER','FIRE_SPREAD'].includes(mode)||clickPts.length<2)return;L.DomEvent.stop(e);const pts=clickPts.map(pointArr);const cat=mode;clickPts=[];save(cat,'POLYLINE',{points:pts},cat==='WATER'?'Zaopatrzenie wodne':'Kierunek rozprzestrzeniania pożaru')});
  const container=map.getContainer();
  const startFree=e=>{if(!kdrMode||mode!=='FREEHAND'||!sheet.classList.contains('open'))return;freeActive=true;freePts=[];map.dragging.disable();const p=e.touches?.[0]||e;const r=container.getBoundingClientRect();freePts.push(map.containerPointToLatLng([p.clientX-r.left,p.clientY-r.top]));temp=L.polyline(freePts,styles.FREEHAND).addTo(map);e.preventDefault()};
  const moveFree=e=>{if(!freeActive)return;const p=e.touches?.[0]||e,r=container.getBoundingClientRect(),ll=map.containerPointToLatLng([p.clientX-r.left,p.clientY-r.top]);if(!freePts.length||map.distance(freePts[freePts.length-1],ll)>2){freePts.push(ll);temp.setLatLngs(freePts)}e.preventDefault()};
  const endFree=e=>{if(!freeActive)return;freeActive=false;map.dragging.enable();if(freePts.length>1){const pts=freePts.map(pointArr);freePts=[];save('FREEHAND','FREEHAND',{points:pts},'Rysunek odręczny')}else stopDraw();e?.preventDefault()};
  container.addEventListener('touchstart',startFree,{passive:false});container.addEventListener('touchmove',moveFree,{passive:false});container.addEventListener('touchend',endFree,{passive:false});container.addEventListener('mousedown',startFree);container.addEventListener('mousemove',moveFree);window.addEventListener('mouseup',endFree);
  $('tacDelete').onclick=async()=>{if(!selectedId)return $('tacState').textContent='Najpierw dotknij rysunku, który chcesz usunąć.';const {error}=await sb.from('incident_drawings').delete().eq('id',selectedId);if(error)return $('tacState').textContent='Nie można usunąć: '+error.message;selectedId=null;await refreshDrawings()};
  $('tacClear').onclick=async()=>{if(!activeIncident)return;if(!confirm('Usunąć wszystkie rysunki taktyczne tego zdarzenia?'))return;const {error}=await sb.from('incident_drawings').delete().eq('incident_id',activeIncident);if(error)return $('tacState').textContent='Nie można wyczyścić: '+error.message;await refreshDrawings();$('tacState').textContent='Warstwa taktyczna wyczyszczona.'};
  $('tacEdit').onclick=()=>{editMode=!editMode;$('tacEdit').classList.toggle('active',editMode);$('tacState').textContent=editMode?'Tryb edycji: dotknij własnego rysunku, potem przeciągaj jego punkty.':'Tryb edycji wyłączony.'};
  map.on('layeradd',ev=>{const l=ev.layer;if(!l?._drawing)return;l.on('edit',async()=>{const d=l._drawing;if(d.created_by!==session.user.id)return;let geometry;if(d.geometry_type==='CIRCLE')geometry={center:pointArr(l.getLatLng()),radius:l.getRadius()};else{const raw=l.getLatLngs(),arr=d.geometry_type==='POLYGON'?(raw[0]||raw):raw;geometry={points:arr.map(pointArr)}}await sb.from('incident_drawings').update({geometry}).eq('id',d.id)})});
  sb.channel('tactical-live').on('postgres_changes',{event:'*',schema:'public',table:'incident_drawings'},()=>refreshDrawings()).on('postgres_changes',{event:'*',schema:'public',table:'incidents'},()=>{refreshIncidents();refreshDrawings()}).subscribe();
  refreshIncidents().then(refreshDrawings);
}
wait();
})();