(()=>{
const wait=()=>{const c=window.firemapCtx;if(!c?.map||!c?.sb||!c?.session){setTimeout(wait,200);return}init(c)};
function init({map,sb,session}){
const root=document.body,$=id=>document.getElementById(id),container=map.getContainer();
const style=document.createElement('style');style.textContent=`
.kdr-main-btn,.tactical-main-btn{position:fixed;z-index:910;left:10px;border:1px solid #ffffff33;color:#fff;font-weight:900;border-radius:12px;padding:9px 11px;box-shadow:0 8px 24px #0008;background:#07111fdd}.kdr-main-btn{top:74px;background:#8a6408e8}.kdr-main-btn.active{background:#ca8a04}.tactical-main-btn{top:120px;background:#7c3aedee;display:none}.tactical-main-btn.show{display:block}.tactical-sheet{position:fixed;z-index:1250;left:50%;bottom:0;transform:translate(-50%,105%);width:min(580px,100%);max-height:82vh;overflow:auto;background:#0a1626;border:1px solid #475569;border-radius:22px 22px 0 0;padding:16px 16px max(18px,env(safe-area-inset-bottom));transition:.2s;box-shadow:0 -20px 50px #0009;color:#fff}.tactical-sheet.open{transform:translate(-50%,0)}.tactical-sheet h2{margin:0 0 5px}.tactical-sheet p{font-size:12px;color:#cbd5e1}.tactical-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tac-btn{min-height:52px;border:1px solid #475569;border-radius:12px;background:#1e293b;color:#fff;font-weight:900}.tac-point{background:#047857}.tac-sector{background:#334155}.tac-water{background:#1d4ed8}.tac-danger{background:#991b1b}.tac-fire{background:#c2410c}.tac-free{background:#6d28d9}.tac-clear{background:#7f1d1d}.tac-select{width:100%;height:44px;background:#111e30;color:#fff;border:1px solid #475569;border-radius:10px}.tac-note{font-size:11px;color:#94a3b8;margin-top:8px}.tac-close{width:100%;min-height:46px;margin-top:10px;border:0;border-radius:11px;background:#334155;color:#fff;font-weight:900}.tac-mini{position:fixed;z-index:1260;left:50%;transform:translateX(-50%);bottom:max(76px,calc(env(safe-area-inset-bottom) + 68px));display:none;align-items:center;gap:7px;background:#07111ff2;border:1px solid #facc15;border-radius:14px;padding:8px 9px;max-width:calc(100vw - 16px)}.tac-mini.show{display:flex}.tac-mini b{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:42vw}.tac-mini button{min-height:34px;border:0;border-radius:8px;background:#334155;color:#fff;font-weight:900;padding:0 9px}.tac-lock{position:fixed;z-index:1240;top:82px;left:50%;transform:translateX(-50%);display:none;background:#111827ee;border:1px solid #facc15;color:#fff;border-radius:999px;padding:7px 11px;font-size:11px;font-weight:900;pointer-events:none}.tac-lock.show{display:block}.tac-point-marker{width:28px;height:28px;border-radius:50%;background:#059669;border:3px solid white;display:grid;place-items:center;color:white;font-weight:900;box-shadow:0 3px 10px #0008}.firemap-draw-mode{touch-action:none!important;cursor:crosshair!important}
`;root.appendChild(style);
const kdr=document.createElement('button');kdr.className='kdr-main-btn';kdr.textContent='⭐ KDR';root.appendChild(kdr);
const tac=document.createElement('button');tac.className='tactical-main-btn';tac.textContent='✏️ TAKTYKA';root.appendChild(tac);
const sheet=document.createElement('div');sheet.className='tactical-sheet';sheet.innerHTML=`<h2>✏️ Taktyka KDR</h2><p>Po wybraniu narzędzia mapa zostaje zablokowana. Rysujesz bez przesuwania podkładu.</p><label>Edytowane zdarzenie</label><select id="tacticalIncident" class="tac-select"></select><div class="tactical-grid" style="margin-top:10px"><button class="tac-btn tac-point" data-tool="POINT">📍 Punkt</button><button class="tac-btn tac-sector" data-tool="SECTOR">⬡ Odcinek bojowy</button><button class="tac-btn tac-water" data-tool="WATER">💧 Linia wodna</button><button class="tac-btn tac-danger" data-tool="DANGER">⭕ Strefa niebezpieczna</button><button class="tac-btn tac-fire" data-tool="FIRE_SPREAD">➡️ Kierunek pożaru</button><button class="tac-btn tac-free" data-tool="FREEHAND">✏️ Odręcznie</button><button class="tac-btn" id="tacDelete">🗑 Usuń zaznaczony</button><button class="tac-btn tac-clear" id="tacClear">🧹 Wyczyść warstwę</button></div><div id="tacState" class="tac-note">Wybierz aktywne zdarzenie i narzędzie.</div><button id="tacClose" class="tac-close">Zamknij</button>`;root.appendChild(sheet);
const mini=document.createElement('div');mini.className='tac-mini';mini.innerHTML='<b id="tacMiniText">Rysowanie</b><button id="tacDone">✓ Gotowe</button><button id="tacTools">Narzędzia</button><button id="tacCancel">Anuluj</button>';root.appendChild(mini);
const lock=document.createElement('div');lock.className='tac-lock';lock.textContent='🔒 TRYB TAKTYKA — MAPA ZABLOKOWANA';root.appendChild(lock);
const styles={SECTOR:{color:'#facc15',weight:4,fillColor:'#facc15',fillOpacity:.08},WATER:{color:'#2563eb',weight:5,dashArray:'10,6'},DANGER:{color:'#dc2626',weight:4,fillColor:'#dc2626',fillOpacity:.12},FIRE_SPREAD:{color:'#f97316',weight:5,dashArray:'8,5'},FREEHAND:{color:'#a855f7',weight:4}};
let kdrMode=false,activeIncident=null,incidentIds=[],tool=null,pts=[],temp=null,startCircle=null,drawing=false,selectedId=null;const layers=new Map();
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function llFromEvent(e){const r=container.getBoundingClientRect();return map.containerPointToLatLng([e.clientX-r.left,e.clientY-r.top])}
function lockMap(){map.dragging.disable();map.touchZoom.disable();map.doubleClickZoom.disable();map.scrollWheelZoom.disable();map.boxZoom.disable();if(map.keyboard)map.keyboard.disable();container.classList.add('firemap-draw-mode');lock.classList.add('show')}
function unlockMap(){map.dragging.enable();map.touchZoom.enable();map.doubleClickZoom.enable();map.scrollWheelZoom.enable();map.boxZoom.enable();if(map.keyboard)map.keyboard.enable();container.classList.remove('firemap-draw-mode');lock.classList.remove('show')}
function clearTemp(){if(temp){map.removeLayer(temp);temp=null}pts=[];startCircle=null;drawing=false}
function stopTool(){tool=null;clearTemp();unlockMap();mini.classList.remove('show')}
async function clearOwnStaleKdr(){if(localStorage.getItem('firemapKdrMode')==='1')return;const id=localStorage.getItem('firemapKdrId');if(!id)return;await sb.from('vehicles').update({status:'BASE',updated_at:new Date().toISOString()}).eq('id',id).eq('vehicle_type','KDR')}
function syncKdr(){kdrMode=localStorage.getItem('firemapKdrMode')==='1';kdr.classList.toggle('active',kdrMode);tac.classList.toggle('show',kdrMode);if(!kdrMode){sheet.classList.remove('open');stopTool();clearOwnStaleKdr()}}
setInterval(syncKdr,3000);syncKdr();
kdr.onclick=()=>{const s=$('statusSheet');if(s)s.classList.add('open')};
tac.onclick=async()=>{if(!kdrMode)return;stopTool();await refreshIncidents();await refreshDrawings();sheet.classList.add('open')};
$('tacClose').onclick=()=>{sheet.classList.remove('open');stopTool()};$('tacTools').onclick=()=>{stopTool();sheet.classList.add('open')};$('tacCancel').onclick=stopTool;
async function refreshIncidents(){const {data,error}=await sb.from('incidents').select('id,kind,description').eq('active',true).order('created_at',{ascending:false});if(error){$('tacState').textContent='Błąd listy zdarzeń: '+error.message;return}incidentIds=(data||[]).map(x=>x.id);const sel=$('tacticalIncident'),old=activeIncident;sel.innerHTML=(data||[]).map(x=>`<option value="${x.id}">${x.kind==='FIRE'?'🔥':'⚠️'} ${esc(x.description||'Zdarzenie')}</option>`).join('');if(old&&incidentIds.includes(old))sel.value=old;activeIncident=sel.value||null;sel.onchange=()=>{activeIncident=sel.value;refreshDrawings()};$('tacState').textContent=activeIncident?'Gotowe — wybierz narzędzie.':'Brak aktywnego zdarzenia.'}
function pointArr(ll){return[+ll.lat,+ll.lng]}
function isPoint(d){return d.geometry_type==='CIRCLE'&&Number(d.geometry?.radius)<=3}
function render(d){const g=d.geometry||{},st={...(styles[d.category]||{}),...(d.style||{})};let l;if(isPoint(d))l=L.marker(g.center,{icon:L.divIcon({className:'',html:'<div class="tac-point-marker">●</div>',iconSize:[30,30],iconAnchor:[15,15]})});else if(d.geometry_type==='CIRCLE')l=L.circle(g.center,{...st,radius:g.radius});else if(d.geometry_type==='POLYGON')l=L.polygon(g.points||[],st);else l=L.polyline(g.points||[],st);l.addTo(map);l.bindPopup('<b>Taktyka KDR</b><br>'+esc(d.label||d.category));l.on('click',()=>{if(!tool)selectedId=d.id});layers.set(d.id,l)}
async function refreshDrawings(){layers.forEach(l=>map.removeLayer(l));layers.clear();if(!incidentIds.length)return;const {data,error}=await sb.from('incident_drawings').select('*').in('incident_id',incidentIds).order('created_at');if(error){$('tacState').textContent='Błąd odczytu taktyki: '+error.message;return}(data||[]).forEach(render)}
async function save(category,type,geometry,label,styleObj={}){const {error}=await sb.from('incident_drawings').insert({incident_id:activeIncident,category,geometry_type:type,geometry,style:styleObj,label,created_by:session.user.id});if(error){stopTool();sheet.classList.add('open');$('tacState').textContent='Błąd zapisu: '+error.message;return}stopTool();await refreshDrawings();$('tacState').textContent='✓ Zapisano i udostępniono.'}
function beginTool(t){if(!activeIncident){$('tacState').textContent='Najpierw wybierz aktywne zdarzenie.';return}stopTool();tool=t;lockMap();sheet.classList.remove('open');mini.classList.add('show');const txt={POINT:'📍 Dotknij miejsca',SECTOR:'⬡ Dotykaj wierzchołków',WATER:'💧 Dotykaj przebiegu',DANGER:'⭕ Środek, potem krawędź',FIRE_SPREAD:'➡️ Dotykaj przebiegu',FREEHAND:'✏️ Rysuj palcem'};$('tacMiniText').textContent=txt[t]||'Rysowanie'}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>beginTool(b.dataset.tool));
function updatePreview(){if(temp)map.removeLayer(temp);if(tool==='SECTOR')temp=L.polygon(pts,styles.SECTOR).addTo(map);else if(tool==='WATER'||tool==='FIRE_SPREAD')temp=L.polyline(pts,styles[tool]).addTo(map);else if(tool==='FREEHAND')temp=L.polyline(pts,styles.FREEHAND).addTo(map)}
function tap(ll){if(tool==='POINT'){save('SECTOR','CIRCLE',{center:pointArr(ll),radius:3},'Punkt taktyczny',{color:'#059669',fillColor:'#10b981',fillOpacity:1,weight:3});return}if(tool==='DANGER'){if(!startCircle){startCircle=ll;if(temp)map.removeLayer(temp);temp=L.circle(ll,{...styles.DANGER,radius:5}).addTo(map);$('tacMiniText').textContent='⭕ Dotknij krawędzi'}else save('DANGER','CIRCLE',{center:pointArr(startCircle),radius:map.distance(startCircle,ll)},'Strefa niebezpieczna',styles.DANGER);return}pts.push(ll);updatePreview();$('tacMiniText').textContent=`${tool==='SECTOR'?'⬡':'✏️'} Punkty: ${pts.length}`}
function finish(){if(tool==='SECTOR'){if(pts.length<3){$('tacMiniText').textContent='Potrzeba 3 punktów';return}save('SECTOR','POLYGON',{points:pts.map(pointArr)},'Odcinek bojowy',styles.SECTOR)}else if(tool==='WATER'||tool==='FIRE_SPREAD'){if(pts.length<2){$('tacMiniText').textContent='Potrzeba 2 punktów';return}const t=tool;save(t,'POLYLINE',{points:pts.map(pointArr)},t==='WATER'?'Zaopatrzenie wodne':'Kierunek pożaru',styles[t])}else if(tool==='FREEHAND'){if(pts.length<2){$('tacMiniText').textContent='Narysuj linię';return}save('FREEHAND','FREEHAND',{points:pts.map(pointArr)},'Rysunek odręczny',styles.FREEHAND)}}
$('tacDone').onclick=finish;
container.addEventListener('pointerdown',e=>{if(!tool)return;e.preventDefault();e.stopPropagation();container.setPointerCapture?.(e.pointerId);const ll=llFromEvent(e);if(tool==='FREEHAND'){drawing=true;pts=[ll];updatePreview()}else tap(ll)},{capture:true});
container.addEventListener('pointermove',e=>{if(!tool||tool!=='FREEHAND'||!drawing)return;e.preventDefault();e.stopPropagation();const ll=llFromEvent(e),last=pts[pts.length-1];if(!last||map.distance(last,ll)>=1){pts.push(ll);updatePreview()}},{capture:true});
container.addEventListener('pointerup',e=>{if(!tool)return;e.preventDefault();e.stopPropagation();if(tool==='FREEHAND'&&drawing){drawing=false;finish()}},{capture:true});
$('tacDelete').onclick=async()=>{if(!selectedId){$('tacState').textContent='Dotknij istniejącego rysunku, a potem usuń.';return}const {error}=await sb.from('incident_drawings').delete().eq('id',selectedId);if(error){$('tacState').textContent=error.message;return}selectedId=null;await refreshDrawings()};
$('tacClear').onclick=async()=>{if(!activeIncident||!confirm('Wyczyścić całą warstwę taktyczną tego zdarzenia?'))return;const {error}=await sb.from('incident_drawings').delete().eq('incident_id',activeIncident);if(error){$('tacState').textContent=error.message;return}await refreshDrawings()};
sb.channel('tactical-stable-v4').on('postgres_changes',{event:'*',schema:'public',table:'incident_drawings'},refreshDrawings).on('postgres_changes',{event:'*',schema:'public',table:'incidents'},async()=>{await refreshIncidents();await refreshDrawings()}).subscribe();
refreshIncidents().then(refreshDrawings);clearOwnStaleKdr();
}
wait();
})();