const fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('./test-runtime/node_modules/@electric-sql/pglite');
const {pgcrypto}=require('./test-runtime/node_modules/@electric-sql/pglite/dist/contrib/pgcrypto.cjs');
const meta=JSON.parse(fs.readFileSync(path.join(__dirname,'test-schema.json'),'utf8'));
const root=process.env.FIREMAP_TEST_ROOT||path.join(__dirname,'..');
const q=s=>'"'+s.replaceAll('"','""')+'"';
(async()=>{
 const db=new PGlite({extensions:{pgcrypto}});
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create role supabase_admin;
 create schema auth;create schema extensions;create extension pgcrypto with schema extensions;
 create table auth.users(id uuid primary key,email text,aud text,role text,created_at timestamptz,updated_at timestamptz);
 create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
 create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;
 grant usage on schema auth,extensions to anon,authenticated,service_role;
 set check_function_bodies=off;`);
 const tables=[...new Set(meta.tables.map(c=>c.table_name))];
 for(const t of tables)await db.exec('create table public.'+q(t)+'('+meta.tables.filter(c=>c.table_name===t).map(c=>q(c.column_name)+' '+c.data_type+(c.is_nullable==='NO'?' not null':'')).join(',')+')');
 for(const c of [...meta.constraints].sort((a,b)=>Number(a.definition.startsWith('FOREIGN'))-Number(b.definition.startsWith('FOREIGN'))))await db.exec('alter table public.'+q(c.tbl)+' add constraint '+q(c.conname)+' '+c.definition);
 for(const f of meta.functions)await db.exec(f);
 for(const c of meta.tables)if(c.column_default)await db.exec('alter table public.'+q(c.table_name)+' alter column '+q(c.column_name)+' set default '+c.column_default);
 for(const t of tables)await db.exec('alter table public.'+q(t)+' enable row level security;grant all on public.'+q(t)+' to anon,authenticated,service_role;');
 for(const p of meta.policies)await db.exec('create policy '+q(p.policyname)+' on public.'+q(p.tablename)+' as '+p.permissive+' for '+p.cmd+' to '+p.roles.map(q).join(',')+(p.qual?' using('+p.qual+')':'')+(p.with_check?' with check('+p.with_check+')':''));
 for(const t of JSON.parse(fs.readFileSync(path.join(__dirname,'test-triggers.json'),'utf8')))await db.exec(t.definition);
 await db.exec(`insert into auth.users(id,email) values('00000000-0000-4000-8000-000000000001','sk@firemap.local'),('00000000-0000-4000-8000-000000000002','osp.test@firemap.local');
 insert into public.firemap_accounts(user_id,role,unit_name) values('00000000-0000-4000-8000-000000000001','SK','KP PSP Radomsko'),('00000000-0000-4000-8000-000000000002','UNIT','OSP Test');
 insert into public.vehicles(id,unit_name,call_sign,vehicle_type,lat,lng,status) values('00000000-0000-4000-8000-000000000010','OSP Test','TEST-1','GBA',51,19,'ON_SCENE');
 insert into public.incidents(kind,lat,lng,created_by) values('FIRE',51,19,'sk@firemap.local');`);
 await db.exec('begin;'+fs.readFileSync(path.join(root,'county_access.sql'),'utf8')+'commit;');
 console.log('PASS: complete migration on a local PostgreSQL schema reconstructed from production metadata');
 const result=await db.exec(fs.readFileSync(path.join(__dirname,'test-counties.sql'),'utf8'));console.log(result.at(-1).rows);
 await db.close();
})().catch(e=>{console.error(e.message,e.detail||'',e.where||'');process.exitCode=1});
