const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const clone=x=>JSON.parse(JSON.stringify(x));const tick=()=>new Promise(r=>setImmediate(r));
class Events{constructor(){this.events={}}on(t,f){(this.events[t]??=[]).push(f);return this}fire(t,e={}){for(const f of this.events[t]||[])f(e);return this}}
class Classes{constructor(){this.s=new Set()}add(x){this.s.add(x)}remove(x){this.s.delete(x)}contains(x){return this.s.has(x)}toggle(x,b){b?this.add(x):this.remove(x)}}
function harness(initial=[]){
 const nodes=new Map(),toolButtons=[],created=[];
 class El extends Events{constructor(id=''){super();this.id=id;this.dataset={};this.classList=new Classes;this.style={};this.value='';this.textContent='';this.disabled=false;this.options=[]}appendChild(x){created.push(x)}addEventListener(t,f){this.on(t,f)}querySelectorAll(sel){return sel==='.tac-color'?[]:[]}focus(){}get innerHTML(){return this.html||''}set innerHTML(v){this.html=v;if(this.id==='tacticalIncident'){this.options=[...v.matchAll(/<option value="([^"]+)"/g)].map(m=>m[1]);this.value=this.options[0]||''}}}
 const node=id=>{if(!nodes.has(id))nodes.set(id,new El(id));return nodes.get(id)};
 for(const name of ['POINT','SECTOR','WATER','DANGER','FREEHAND','FIRE_SPREAD']){const b=new El;b.dataset.tac=name;toolButtons.push(b)}
 let seq=0;const storage=new Map([['firemapKdrMode','1']]);const window=new Events;window.addEventListener=window.on;window.dispatchEvent=e=>window.fire(e.type,e);
 const document={body:new El,head:new El,createElement:()=>new El,getElementById:node,querySelectorAll:s=>s==='[data-tac]'?toolButtons:[],addEventListener(){}};
 class Layer extends Events{constructor(points,options={}){super();this.points=clone(points);this.options=options;this.dragging={enable(){},disable(){}};this._leaflet_id=++seq}addTo(m){this.map=m;m._layers[this._leaflet_id]=this;m.fire('layeradd',{layer:this});return this}bindPopup(x){this.popup=x;return this}bindTooltip(){return this}unbindPopup(){return this}setLatLng(p){this.points=clone(p);return this}getLatLng(){const p=this.points;return Array.isArray(p)?{lat:p[0],lng:p[1]}:p}getLatLngs(){return this.points.map(p=>Array.isArray(p)?{lat:p[0],lng:p[1]}:p)}setLatLngs(p){this.points=clone(p);return this}getElement(){return null}}
 class Polyline extends Layer{}class Polygon extends Polyline{}
 const L={marker:(p,o)=>new Layer(p,o),circle:(p,o)=>new Layer(p,o),polygon:(p,o)=>new Polygon(p,o),polyline:(p,o)=>new Polyline(p,o),divIcon:o=>o,Polyline,Polygon,DomEvent:{stop(){}}};
 const map=new Events;map._layers={};map.eachLayer=f=>Object.values(map._layers).forEach(f);map.removeLayer=l=>{if(!map._layers[l._leaflet_id])return;delete map._layers[l._leaflet_id];map.fire('layerremove',{layer:l});l.fire('remove')};map.hasLayer=l=>!!map._layers[l._leaflet_id];map.getContainer=()=>node('map');map.distance=(a,b)=>Math.hypot((a.lat??a[0])-(b.lat??b[0]),(a.lng??a[1])-(b.lng??b[1]))*100000;
 for(const k of ['dragging','touchZoom','doubleClickZoom','scrollWheelZoom','boxZoom','keyboard'])map[k]={enable(){this.on=true},disable(){this.on=false},enabled(){return this.on},on:true};
 const calls=[];let fail=false;let server=clone(initial);const sb={channel:()=>({on(){return this},subscribe(){}}),from:table=>{let op='select',payload,filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},in(k,v){filters[k]=v;return q},order(){return q},delete(){op='delete';return q},upsert(rows){op='upsert';payload=clone(rows);return q},then(resolve){if(op!=='select')calls.push({op,payload,filters});if(fail&&op==='upsert')return Promise.resolve({error:{message:'offline'}}).then(resolve);return Promise.resolve({data:table==='incidents'?[{id:'inc1',kind:'MZ',description:'TEST'}]:server}).then(resolve)}};return q}};
 const ctx={window,document,L,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},crypto:{randomUUID:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`},CustomEvent:class{constructor(type,o){this.type=type;this.detail=o.detail}},setInterval(){},setTimeout:f=>{queueMicrotask(f)},confirm:()=>true,console};window.firemapCtx={map,sb,session:{user:{id:'user1'}}};vm.createContext(ctx);
 vm.runInContext(fs.readFileSync('tactical-ui-core.js','utf8'),ctx);
 return{ctx,window,map,node,toolButtons,calls,storage,Layer,get api(){return window.firemapTacticalEditor},start(t){toolButtons.find(b=>b.dataset.tac===t).onclick()},click(lat,lng){map.fire('click',{latlng:{lat,lng}})},draft(){return JSON.parse(storage.get('firemap:tactical:draft:inc1:user1')||'{}').draft||[]},fail(v){fail=v}};
}
async function run(){
 const h=harness();await tick();
 h.start('WATER');h.click(51,19);h.click(51.01,19.01);h.click(51.02,19.02);h.node('tacMiniUndo').onclick();assert.equal(h.api.points.length,2);assert.equal(h.draft().length,0);h.node('tacDone').onclick();assert.equal(h.draft().length,1);assert.equal(h.draft()[0].geometry.points.length,2);
 h.start('SECTOR');h.click(52,20);h.node('tacMiniUndo').onclick();assert.equal(h.draft().length,1);assert.equal(h.api.points.length,0);h.node('tacCancel').onclick();
 h.start('DANGER');h.click(51,19);h.node('tacMiniUndo').onclick();assert.equal(h.api.center,null);assert.equal(h.draft().length,1);h.node('tacCancel').onclick();
 h.start('POINT');h.click(51,19);h.node('tacPointName').value='Punkt';h.node('tacPointSave').onclick();let d=h.draft().at(-1);assert.equal(h.draft().length,2);
 assert.equal(h.api.updateItem(d.local_key,{geometry:{center:[52,20],radius:3}},'moved'),true);assert.equal(h.draft().at(-1).geometry.center[0],52);h.node('tacUndo').onclick();assert.equal(h.draft().at(-1).geometry.center[0],51);
 h.api.updateItem(d.local_key,{label:'nowa nazwa'});h.node('tacUndo').onclick();assert.equal(h.draft().at(-1).label,'Punkt');
 const layer=Object.values(h.map._layers).find(l=>l._firemapLocalKey===d.local_key);layer.fire('click');h.node('tacDelete').onclick();assert.equal(h.draft().length,1);h.node('tacUndo').onclick();assert.equal(h.draft().length,2);
 h.node('tacClear').onclick();assert.equal(h.draft().length,0);h.node('tacUndo').onclick();assert.equal(h.draft().length,2);
 h.fail(true);await h.node('tacPublish').onclick();assert.equal(h.calls.filter(x=>x.op==='delete').length,0);assert.equal(h.draft().length,2);const firstIds=h.calls.at(-1).payload.map(d=>d.id);h.fail(false);await h.node('tacPublish').onclick();assert.deepEqual(h.calls.at(-1).payload.map(d=>d.id),firstIds);
 h.node('tacClear').onclick();await h.node('tacPublish').onclick();assert.equal(h.calls.at(-1).op,'delete');assert.equal(h.calls.at(-1).filters.created_by,'user1');
 const before=h.calls.length;h.node('tacUndo').onclick();await h.node('tacPublish').onclick();assert.equal(h.calls[before].op,'upsert');
 // The point and sector adapters must update the core draft, never their own stale storage copy.
 for(const file of ['tactical-point-drag.js','tactical-sector-drag.js','tactical-sector-description.js'])vm.runInContext(fs.readFileSync(file,'utf8'),h.ctx);
 await tick();let point=Object.values(h.map._layers).find(l=>h.api.getItem(l._firemapLocalKey)?.style?.point);point.fire('dragstart');point.setLatLng([53,21]);point.fire('dragend');assert.equal(h.draft().find(x=>x.style?.point).geometry.center[0],53);h.api.undo();assert.equal(h.draft().find(x=>x.style?.point).geometry.center[0],51);
 h.start('SECTOR');h.click(51,19);h.click(51.01,19);h.click(51,19.01);h.node('tacDone').onclick();await tick();const sector=Object.values(h.map._layers).find(l=>h.api.getItem(l._firemapLocalKey)?.geometry_type==='POLYGON');sector.fire('click');await tick();const handle=Object.values(h.map._layers).find(l=>l.options.zIndexOffset===1800);assert.ok(handle);handle.fire('dragstart');handle.setLatLng([54,22]);handle.fire('drag',{target:handle});handle.fire('dragend',{target:handle});assert.equal(h.draft().at(-1).geometry.points[0][0],54);h.api.undo();assert.equal(h.draft().at(-1).geometry.points[0][0],51);
 const sec2=Object.values(h.map._layers).find(l=>h.api.getItem(l._firemapLocalKey)?.geometry_type==='POLYGON');sec2.fire('dblclick');h.node('fmSectorName').value='Odcinek II';h.node('fmSectorDesc').value='Obrona';h.node('fmSectorSave').onclick();assert.equal(h.draft().at(-1).style.sectorDescription,'Obrona');h.api.undo();assert.equal(h.draft().at(-1).label,'Odcinek bojowy');
 console.log('PASS: vertex undo, danger-center undo, move/rename/delete/clear undo, stable retry IDs, save failure preserves draft, scoped delete, point drag, large sector drag, sector description undo');
}
run().catch(e=>{console.error(e);process.exitCode=1});
